# Generated by Django 5.1.4 on 2025-01-24 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TontineCollective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('limite_member', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('frequence', models.CharField(choices=[('jour', 'Chaque jour'), ('semaine', 'Chaque semaine'), ('mois', 'Une fois par mois')], default='jour', max_length=12)),
                ('order_paiemement', models.IntegerField(choices=[(1, 'Aléatoire'), (2, "Par ordre d'adhésion")], default=1)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_tontine_collective', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='member_tontines_collective', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TontineIndividuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_tontine_individuelle', to=settings.AUTH_USER_MODEL)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memeber_tontine_individuelle', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='Tontine',
        ),
    ]
