# Generated by Django 5.1.4 on 2025-01-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0002_tontinecollective_tontineindividuelle_delete_tontine'),
    ]

    operations = [
        migrations.AddField(
            model_name='tontinecollective',
            name='qr_code',
            field=models.ImageField(default=1, upload_to='tontine/media/'),
            preserve_default=False,
        ),
    ]
