# Generated by Django 5.1.4 on 2025-01-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0003_tontinecollective_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tontinecollective',
            name='qr_code',
            field=models.ImageField(upload_to='tontine_qrcode/'),
        ),
    ]
