# Generated by Django 5.1.4 on 2025-01-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0004_alter_tontinecollective_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tontinecollective',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tontine_qrcode/'),
        ),
    ]
