# Generated by Django 5.1.4 on 2025-02-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0005_alter_tontinecollective_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tontinecollective',
            name='periode_amount',
            field=models.IntegerField(default=0),
        ),
    ]
