# Generated by Django 5.1.4 on 2025-02-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0006_tontinecollective_periode_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tontinecollective',
            name='recipient_tontine_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tontinecollective',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TontineIndividuelle',
        ),
    ]
