# Generated by Django 5.1.4 on 2025-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0007_tontinecollective_recipient_tontine_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tontinecollective',
            name='periode_count',
            field=models.IntegerField(default=0),
        ),
    ]
