# Generated by Django 5.1.4 on 2025-02-28 02:00
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0009_blocked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocked_user',
            name='tontine',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='tontine.tontinecollective'),
            preserve_default=False,
        ),
    ]
