# Generated by Django 5.1.4 on 2025-01-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number_phone',
            new_name='phone_number',
        ),
    ]
