# Generated by Django 5.1.4 on 2025-01-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_number_phone_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='media/user'),
        ),
    ]
