# Generated by Django 5.1.4 on 2025-02-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_phone_number_alter_user_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='statue',
            field=models.CharField(choices=[('user', 'utilisateur'), ('admin', 'gestionnaire')], default='user', max_length=30),
        ),
    ]
