# Generated by Django 5.1.4 on 2025-02-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_individuelle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tontineindividuelle',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tontineindividuelle',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
