# Generated by Django 5.1.4 on 2025-02-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_individuelle', '0002_alter_tontineindividuelle_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tontineindividuelle',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
