# Generated by Django 5.1.4 on 2025-02-05 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquitement',
            name='moyen',
            field=models.CharField(choices=[('cash', 'payement cash'), ('orange', 'Orange Money'), ('paycard', 'Paycard')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payement', to=settings.AUTH_USER_MODEL),
        ),
    ]
