# Generated by Django 5.1.4 on 2025-02-13 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0002_alter_acquitement_moyen_alter_payment_recipient'),
        ('tontine_individuelle', '0002_alter_tontineindividuelle_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquitementIndividuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('moyen', models.CharField(choices=[('cash', 'payement cash'), ('orange', 'Orange Money'), ('paycard', 'Paycard')], default='cash', max_length=10)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquitement_individuelle', to='tontine_individuelle.tontineindividuelle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
