# Generated by Django 5.1.4 on 2025-02-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0004_paymentindividuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquitement',
            name='count_paiement',
            field=models.IntegerField(default=0),
        ),
    ]
