# Generated by Django 5.1.4 on 2025-02-28 00:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0005_acquitement_count_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquitement',
            name='count_paiement',
        ),
    ]
