//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dounoh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voiture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voiture()
        {
            this.Passager = new HashSet<Passager>();
        }
    
        public int id { get; set; }
        public string marque { get; set; }
        public string modele { get; set; }
        public string immatriculation { get; set; }
        public Nullable<int> chauffeur_id { get; set; }
        public Nullable<int> place { get; set; }
        public string depart { get; set; }
        public string destination { get; set; }
        public string heure_depart { get; set; }
    
        public virtual Chauffeur Chauffeur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passager> Passager { get; set; }
    }
}
